### ISSUE TITLE
rawurlencode() expects parameter 1 to be string, bool given in Escaper.php:246

### ISSUE THREAD

**Issue by purpletreesoft** [laminas/laminas-escaper#24] opened 2021-06-25 18:29 UTC
The latest version passes int argument to rawurlencode, where string is expected.

problem is at line 246:

`return rawurlencode($string);
`

possible solution:

`return rawurlencode(strval($string));`

**Comment by purpletreesoft** [comment] 2021-06-25 18:33
This issue was observed in Magento 2 CE, when the latest Laminas was pulled.

**Comment by purpletreesoft** [comment] 2021-06-25 18:34
I see another issue related to strict checks introduced. Perhaps that commit fixes this issue too?

**Comment by froschdesign** [comment] 2021-06-26 08:52
Duplicate of #20 

See also: https://github.com/laminas/laminas-escaper/issues/21#issuecomment-868542534

**Closed as completed by froschdesign** 2021-06-26 08:52 UTC
Labels: BC Break, Duplicate, Invalid
