### ISSUE TITLE
Error file Escaper.php:246 ( Solved )

### ISSUE THREAD

**Issue by adorobeleza** [laminas/laminas-escaper#25] opened 2021-06-25 21:42 UTC
### Bug Report

After updating magento 2.4.2 to blades escaper 2.7.1. I'm getting error in /Escaper.php file

![error](https://user-images.githubusercontent.com/80371175/123487806-0c912d00-d5e5-11eb-9540-9e3821ff7e7b.PNG)

|    Q        |   A
|------------ | ------
| Version(s)  | 2.7.1

**Comment by froschdesign** [comment] 2021-06-26 08:52
Duplicate of #20 

See also: https://github.com/laminas/laminas-escaper/issues/21#issuecomment-868542534

**Closed as completed by froschdesign** 2021-06-26 08:52 UTC
Labels: Bug, Duplicate, Invalid
